### ISSUE TITLE
admin-default.json ignored in dockerized central-collector

### ISSUE THREAD

**Issue by fabioportieri** [glowroot/glowroot#1066]
Hello

i'm trying to setup a custom admin.json for my central collector, i can see my json file is present on the container but when i connect to the web console i can see the usual default configuration instead of the one i provided:

admin-default.json
```
{
  "users": [
    {
      "username": "admin",
      "passwordHash": ".....:500000",
      "roles": [
        "Administrator"
      ]
    },
    {
      "username": "anonymous",
      "roles": [
        "Anonymous"
      ]
    }
  ],
  "roles": [
    {
      "name": "Administrator",
      "permissions": [
        "admin",
        "agent:*:config",
        "agent:*:error",
        "agent:*:incident",
        "agent:*:jvm",
        "agent:*:syntheticMonitor",
        "agent:*:transaction"
      ]
    }
  ],
  "web": {
    "sessionTimeoutMinutes": 30,
    "sessionCookieName": "GLOWROOT_SESSION_ID"
  },
  "storage": {
    "rollupExpirationHours": [
      48,
      336,
      2160,
      8760
    ],
    "queryAndServiceCallRollupExpirationHours": [
      48,
      168,
      720,
      720
    ],
    "profileRollupExpirationHours": [
      48,
      24,
      720,
      721
    ],
    "traceExpirationHours": 144
  }
}
```

Dockerfile:
```
FROM glowroot/glowroot-central:0.14.1

COPY ./glowroot-central.properties /usr/share/glowroot-central/glowroot-central.properties
COPY ./admin-default.json /usr/share/glowroot-central/
```

docker compose file:
```
version: "3.8"

networks:
  nut_net:
    driver: bridge
    name: nut_net

services:
  cassandra:
    container_name: cassandra
    build:
      context: ./cassandra
    restart: always
    volumes:
      - cassandra-volume:/var/lib/cassandra
    networks:
      - nut_net
  glowroot:
    container_name: glowroot
    build:
      context: ./glowroot
    restart: always
    depends_on:
      - cassandra
    ports:
      - "4000:4000"
      - "8181:8181"
    networks:
      - nut_net
volumes:
  cassandra-volume:
    driver: local   
  glowroot-data:
    driver: local
```

Thank you for any assistance
